version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/jenkins/data:/var/jenkins_home
      - /srv/jenkins:/home
    environment:
      - VIRTUAL_HOST=jenkins.orwell.ovh
      - VIRTUAL_PORT=8080
  nginxproxy:
    image: jwilder/nginx-proxy
    container_name: nginxproxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /srv/jenkins/certs:/etc/nginx/certs